name: Jasmine Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: |
          yarn install
      - uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: public/
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with: 
          name: build artifacts
          path: public
      - name: use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '10.21.0'
        run: |
          yarn install
          yarn test
