name: Jasmine Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with: 
          name: webpack artifacts
          path: public
      - uses: actions/setup-node@v2
        with:
          node-version: '10.14.0'
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with: 
          name: webpack artifacts
          path: public
      - uses: actions/setup-node@v2
        with:
          node-version: '10.14.0'
      - run: yarn lint 
